create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats (id) on delete cascade,
  owner_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_limits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  token_refresh_date date not null default current_date,
  remaining_tokens int not null default 100000
);

alter table public.chats enable row level security;
alter table public.messages enable row level security;
alter table public.user_limits enable row level security;

drop policy if exists "chats_select_own" on public.chats;
create policy "chats_select_own"
on public.chats for select
using (auth.uid() = owner_id);

drop policy if exists "chats_insert_own" on public.chats;
create policy "chats_insert_own"
on public.chats for insert
with check (auth.uid() = owner_id);

drop policy if exists "chats_delete_own" on public.chats;
create policy "chats_delete_own"
on public.chats for delete
using (auth.uid() = owner_id);

drop policy if exists "messages_select_own" on public.messages;
create policy "messages_select_own"
on public.messages for select
using (
  exists (
    select 1
    from public.chats
    where chats.id = messages.chat_id
      and chats.owner_id = auth.uid()
  )
);

drop policy if exists "messages_insert_own" on public.messages;
create policy "messages_insert_own"
on public.messages for insert
with check (
  auth.uid() = owner_id
  and exists (
    select 1
    from public.chats
    where chats.id = messages.chat_id
      and chats.owner_id = auth.uid()
  )
);

drop policy if exists "messages_delete_own" on public.messages;
create policy "messages_delete_own"
on public.messages for delete
using (
  exists (
    select 1
    from public.chats
    where chats.id = messages.chat_id
      and chats.owner_id = auth.uid()
  )
);

-- SELECT LIMITS
drop policy if exists "user_limits_select_own" on public.user_limits;
create policy "user_limits_select_own"
on public.user_limits for select
using (auth.uid() = user_id);

-- INSERT LIMITS
drop policy if exists "user_limits_insert_own" on public.user_limits;
create policy "user_limits_insert_own"
on public.user_limits for insert
with check (auth.uid() = user_id);

-- UPDATE LIMITS
drop policy if exists "user_limits_update_own" on public.user_limits;
create policy "user_limits_update_own"
on public.user_limits for update
using (auth.uid() = user_id);

insert into public.user_limits (user_id)
select id
from auth.users
on conflict (user_id) do nothing;

create or replace function public.handle_new_user_session()
returns trigger as $$
begin
  insert into public.user_sessions (user_id)
  values (new.id);
  insert into public.user_limits (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created_session
after insert on auth.users
for each row execute procedure public.handle_new_user_session();
